import { getAdminEmail } from '../utils/admin';
import React, { useEffect, useState } from "react"
import { motion, AnimatePresence } from "motion/react"
import { 
  Plus, Edit2, Trash2, Copy, Eye, X, Loader2, Sparkles, Check, 
  Layers, Utensils, AlertTriangle, Flame, ShieldAlert, Award, 
  TrendingUp, IndianRupee, Calendar, Users, Search, CheckCircle, 
  HelpCircle, Clock, ChevronRight, Truck, Download, EyeOff, 
  SlidersHorizontal, CheckSquare, Square, RefreshCw, Archive, Undo2
} from "lucide-react"
import { planService } from "../services/plans"
import { SubscriptionPlan, Subscription } from "../types"
import { useAuth } from "../contexts/auth-context"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Card, CardContent } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { PlanAnalytics } from "../components/plan-analytics"
import { PlanWizard } from "../components/plan-wizard"

// UI Tabs for operations
type ViewTab = "catalog" | "analytics"

export default function SubscriptionPlansPage() {
  const { user } = useAuth()
  const [plans, setPlans] = useState<any[]>([])
  const [subscriptions, setSubscriptions] = useState<Subscription[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [activeTab, setActiveTab] = useState<ViewTab>("catalog")

  // Search & Filter state
  const [searchQuery, setSearchQuery] = useState("")
  const [selectedCategory, setSelectedCategory] = useState("All")
  const [selectedStatus, setSelectedStatus] = useState("All")
  const [selectedDiet, setSelectedDiet] = useState("All")
  const [sortBy, setSortBy] = useState<"name" | "price" | "displayOrder" | "createdAt">("displayOrder")
  const [sortOrder, setSortOrder] = useState<"asc" | "desc">("asc")

  // Pagination
  const [currentPage, setCurrentPage] = useState(1)
  const itemsPerPage = 8

  // Bulk selections
  const [selectedPlanIds, setSelectedPlanIds] = useState<string[]>([])

  // Column Visibility States
  const [visibleColumns, setVisibleColumns] = useState<Record<string, boolean>>({
    image: true,
    name: true,
    code: true,
    category: true,
    duration: true,
    mealsPerDay: true,
    totalMeals: true,
    dietType: true,
    goal: true,
    nutrition: true,
    price: true,
    subscribers: true,
    revenue: true,
    status: true,
    actions: true
  })
  const [showColumnDropdown, setShowColumnDropdown] = useState(false)

  // Modals & Forms triggering
  const [isWizardOpen, setIsWizardOpen] = useState(false)
  const [editingPlan, setEditingPlan] = useState<any>(null)
  const [previewPlan, setPreviewPlan] = useState<any>(null)

  // Realtime Listeners
  useEffect(() => {
    setLoading(true)
    const unsubscribePlans = planService.subscribePlans(
      (data) => {
        setPlans(data)
        setLoading(false)
      },
      (err) => {
        setError(err.message || "Failed to load subscription plans")
        setLoading(false)
      }
    )

    const unsubscribeSubs = planService.subscribeAllSubscriptions(
      (data) => {
        setSubscriptions(data)
      },
      (err) => {
        console.error("Failed to load active subscriptions:", err)
      }
    )

    return () => {
      unsubscribePlans()
      unsubscribeSubs()
    }
  }, [])

  // Subscriber count helpers
  const activeSubs = subscriptions.filter(sub => sub.status === "Active" || sub.status === "Paused")
  const getSubscribersForPlan = (planId: string) => {
    return activeSubs.filter(sub => sub.planId === planId).length
  }

  // Monthly Revenue generated by plan
  const getMonthlyRevenueForPlan = (plan: any) => {
    const subscriberCount = getSubscribersForPlan(plan.id)
    return subscriberCount * (plan.offerPrice || plan.price || 0)
  }

  // Metrics calculators (Section 1 Enterprise Dashboard)
  const totalActiveSubscribers = activeSubs.length
  const totalRevenue = plans.reduce((sum, p) => sum + getMonthlyRevenueForPlan(p), 0)
  
  const metrics = {
    totalPlans: plans.filter(p => p.status !== "SoftDeleted").length,
    activePlans: plans.filter(p => p.status === "Active").length,
    draftPlans: plans.filter(p => p.status === "Draft").length,
    inactivePlans: plans.filter(p => p.status === "Inactive").length,
    trialPlans: plans.filter(p => p.duration <= 5 || (p.badge && p.badge.toLowerCase().includes("trial"))).length,
    activeSubscribers: totalActiveSubscribers,
    monthlyRevenue: totalRevenue,
    expiringPlansCount: plans.filter(p => p.status === "Upcoming" || p.status === "Hidden").length
  }

  // Handle plan saving/updating
  const handleSavePlan = async (planData: any) => {
    const adminId = user?.id || "admin-system"
    const adminEmail = getAdminEmail(user)

    if (editingPlan) {
      await planService.updatePlan(editingPlan.id, planData, adminId, adminEmail)
    } else {
      await planService.createPlan(planData, adminId, adminEmail)
    }
    setEditingPlan(null)
  }

  // Table sorting, filtering, and searches
  const filteredPlans = plans
    .filter(p => p.status !== "SoftDeleted") // Exclude soft deleted plans from view
    .filter(p => {
      const matchesSearch = 
        (p.planName || p.name || "").toLowerCase().includes(searchQuery.toLowerCase()) ||
        (p.planCode || "").toLowerCase().includes(searchQuery.toLowerCase()) ||
        (p.description || "").toLowerCase().includes(searchQuery.toLowerCase())
      
      const matchesCategory = selectedCategory === "All" || p.category === selectedCategory
      const matchesStatus = selectedStatus === "All" || p.status === selectedStatus
      const matchesDiet = selectedDiet === "All" || p.dietType === selectedDiet

      return matchesSearch && matchesCategory && matchesStatus && matchesDiet
    })
    .sort((a, b) => {
      let fieldA: any = ""
      let fieldB: any = ""

      if (sortBy === "name") {
        fieldA = (a.planName || a.name || "").toLowerCase()
        fieldB = (b.planName || b.name || "").toLowerCase()
      } else if (sortBy === "price") {
        fieldA = a.offerPrice || a.price || 0
        fieldB = b.offerPrice || b.price || 0
      } else if (sortBy === "displayOrder") {
        fieldA = a.displayOrder || 999
        fieldB = b.displayOrder || 999
      } else {
        fieldA = a.createdAt || ""
        fieldB = b.createdAt || ""
      }

      if (fieldA < fieldB) return sortOrder === "asc" ? -1 : 1
      if (fieldA > fieldB) return sortOrder === "asc" ? 1 : -1
      return 0
    })

  // Pagination calculation
  const totalPages = Math.ceil(filteredPlans.length / itemsPerPage)
  const currentPlans = filteredPlans.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  )

  // Select/Deselect handlers
  const handleSelectAll = () => {
    if (selectedPlanIds.length === currentPlans.length) {
      setSelectedPlanIds([])
    } else {
      setSelectedPlanIds(currentPlans.map(p => p.id))
    }
  }

  const handleSelectRow = (id: string) => {
    if (selectedPlanIds.includes(id)) {
      setSelectedPlanIds(prev => prev.filter(pId => pId !== id))
    } else {
      setSelectedPlanIds(prev => [...prev, id])
    }
  }

  // Bulk Actions
  const handleBulkStatusChange = async (newStatus: string) => {
    if (selectedPlanIds.length === 0) return
    const adminId = user?.id || "admin"
    const adminEmail = getAdminEmail(user)

    try {
      setLoading(true)
      for (const id of selectedPlanIds) {
        await planService.updatePlan(id, { status: newStatus as any }, adminId, adminEmail)
      }
      setSelectedPlanIds([])
    } catch (err) {
      console.error(err)
      alert("Error executing bulk operation")
    } finally {
      setLoading(false)
    }
  }

  const handleBulkSoftDelete = async () => {
    if (selectedPlanIds.length === 0) return
    if (!confirm("Are you sure you want to soft-delete selected plans?")) return
    const adminId = user?.id || "admin"
    const adminEmail = getAdminEmail(user)

    try {
      setLoading(true)
      for (const id of selectedPlanIds) {
        await planService.updatePlan(id, { status: "SoftDeleted" as any }, adminId, adminEmail)
      }
      setSelectedPlanIds([])
    } catch (err) {
      console.error(err)
    } finally {
      setLoading(false)
    }
  }

  // Single Actions
  const handleDuplicate = async (planId: string) => {
    const adminId = user?.id || "admin"
    const adminEmail = getAdminEmail(user)
    try {
      await planService.duplicatePlan(planId, adminId, adminEmail)
    } catch (err) {
      console.error(err)
      alert("Failed to duplicate plan")
    }
  }

  const handleArchive = async (planId: string) => {
    const adminId = user?.id || "admin"
    const adminEmail = getAdminEmail(user)
    try {
      await planService.updatePlan(planId, { status: "Archived" as any }, adminId, adminEmail)
    } catch (err) {
      console.error(err)
    }
  }

  const handleSoftDelete = async (planId: string) => {
    if (!confirm("Are you sure you want to soft delete this subscription plan?")) return
    const adminId = user?.id || "admin"
    const adminEmail = getAdminEmail(user)
    try {
      await planService.updatePlan(planId, { status: "SoftDeleted" as any }, adminId, adminEmail)
    } catch (err) {
      console.error(err)
    }
  }

  // EXPORT CSV Function
  const exportToCSV = () => {
    const headers = [
      "Plan Name", "Plan Code", "Category", "Duration Days", "Meals Per Day", 
      "Total Meals", "Diet Type", "Health Goal", "Calories (kcal)", "Protein (g)", 
      "Carbs (g)", "Fats (g)", "Original Price", "Offer Price", "Final Price", "Status"
    ]

    const csvRows = [headers.join(",")]

    for (const p of filteredPlans) {
      const row = [
        `"${p.planName || p.name || ''}"`,
        `"${p.planCode || ''}"`,
        `"${p.category || ''}"`,
        p.duration,
        p.mealsPerDay,
        p.totalMeals,
        `"${p.dietType || ''}"`,
        `"${p.goal || ''}"`,
        p.calories,
        p.protein,
        p.carbs,
        p.fat,
        p.price,
        p.offerPrice,
        p.finalPrice || (p.offerPrice || p.price),
        `"${p.status}"`
      ]
      csvRows.push(row.join(","))
    }

    const blob = new Blob([csvRows.join("\n")], { type: "text/csv;charset=utf-8;" })
    const link = document.createElement("a")
    const url = URL.createObjectURL(blob)
    link.setAttribute("href", url)
    link.setAttribute("download", `TaazaBites_Subscription_Plans_${new Date().toISOString().split('T')[0]}.csv`)
    link.style.visibility = "hidden"
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  // EXPORT EXCEL (Lightweight Excel XML table layout)
  const exportToExcel = () => {
    let rowData = ""
    for (const p of filteredPlans) {
      rowData += `
        <tr>
          <td>${p.planName || p.name || ''}</td>
          <td>${p.planCode || ''}</td>
          <td>${p.category || ''}</td>
          <td>${p.duration}</td>
          <td>${p.mealsPerDay}</td>
          <td>${p.totalMeals}</td>
          <td>${p.dietType || ''}</td>
          <td>${p.goal || ''}</td>
          <td>${p.calories}</td>
          <td>${p.protein}</td>
          <td>${p.price}</td>
          <td>${p.offerPrice}</td>
          <td>${p.finalPrice || (p.offerPrice || p.price)}</td>
          <td>${p.status}</td>
        </tr>`
    }

    const excelTemplate = `
      <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
      <head><meta charset="UTF-8"></head>
      <body>
        <table border="1">
          <tr style="background-color: #10b981; color: white; font-weight: bold;">
            <th>Plan Name</th>
            <th>Plan Code</th>
            <th>Category</th>
            <th>Duration Days</th>
            <th>Meals Per Day</th>
            <th>Total Meals</th>
            <th>Diet Type</th>
            <th>Health Goal</th>
            <th>Calories (kcal)</th>
            <th>Protein (g)</th>
            <th>Original Price</th>
            <th>Offer Price</th>
            <th>Final Price</th>
            <th>Status</th>
          </tr>
          ${rowData}
        </table>
      </body>
      </html>`

    const blob = new Blob([excelTemplate], { type: "application/vnd.ms-excel" })
    const link = document.createElement("a")
    const url = URL.createObjectURL(blob)
    link.setAttribute("href", url)
    link.setAttribute("download", `TaazaBites_Subscription_Plans_${new Date().toISOString().split('T')[0]}.xls`)
    link.style.visibility = "hidden"
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  return (
    <div className="min-h-screen bg-black text-zinc-100 p-6 md:p-8 space-y-8 select-none">
      
      {/* Top Welcome Panel */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <div className="flex items-center gap-2">
            <Badge className="bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20 border-emerald-500/20 font-bold uppercase tracking-widest text-[10px]">
              TaazaBites Enterprise Admin Panel
            </Badge>
            <span className="text-zinc-700 text-xs font-mono">• v1.0 Production-Ready</span>
          </div>
          <h1 className="text-3xl font-black text-white mt-1 tracking-tight">Subscription Plan Management</h1>
          <p className="text-xs text-zinc-500 mt-1">Configure clinical nutrition tiers, customized pricing, delivery regions and policy parameters</p>
        </div>

        <div className="flex items-center gap-3">
          <Button
            onClick={() => {
              setEditingPlan(null)
              setIsWizardOpen(true)
            }}
            className="bg-emerald-500 hover:bg-emerald-400 text-black font-black rounded-xl shadow-lg shadow-emerald-500/10"
          >
            <Plus className="mr-1.5 h-4.5 w-4.5 stroke-[3px]" /> Formulate Plan
          </Button>
        </div>
      </div>

      {/* METRICS ROW (Section 1 Enterprise Dashboard) */}
      <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">
        {[
          { label: "Total Plans", value: metrics.totalPlans, icon: Layers, color: "text-zinc-400" },
          { label: "Active Plans", value: metrics.activePlans, icon: CheckCircle, color: "text-emerald-400" },
          { label: "Draft / Pending", value: metrics.draftPlans, icon: Clock, color: "text-amber-400" },
          { label: "Trial Packages", value: metrics.trialPlans, icon: Award, color: "text-indigo-400" },
          { label: "Live Subscribers", value: metrics.activeSubscribers, icon: Users, color: "text-blue-400" },
          { label: "Est. Revenue", value: `₹${metrics.monthlyRevenue.toLocaleString()}`, icon: IndianRupee, color: "text-emerald-500" }
        ].map((met, idx) => {
          const Icon = met.icon
          return (
            <div key={idx} className="bg-zinc-950 border border-zinc-900/80 p-5 rounded-2xl flex items-center justify-between">
              <div className="space-y-1">
                <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest block">{met.label}</span>
                <span className="text-xl font-black text-white block">{met.value}</span>
              </div>
              <div className={`h-10 w-10 rounded-xl bg-zinc-900/60 flex items-center justify-center ${met.color}`}>
                <Icon className="h-5 w-5" />
              </div>
            </div>
          )
        })}
      </div>

      {/* TABS SELECTOR */}
      <div className="flex items-center justify-between border-b border-zinc-900 pb-2">
        <div className="flex items-center gap-2">
          <button
            onClick={() => setActiveTab("catalog")}
            className={`px-4 py-2 text-xs font-black rounded-lg transition-all ${
              activeTab === "catalog" 
                ? "bg-zinc-900 text-emerald-400" 
                : "text-zinc-500 hover:text-white"
            }`}
          >
            Active Catalogs
          </button>
          <button
            onClick={() => setActiveTab("analytics")}
            className={`px-4 py-2 text-xs font-black rounded-lg transition-all ${
              activeTab === "analytics" 
                ? "bg-zinc-900 text-emerald-400" 
                : "text-zinc-500 hover:text-white"
            }`}
          >
            Realtime Analytics
          </button>
        </div>

        <div className="flex items-center gap-2">
          {/* Export options */}
          <Button variant="outline" size="xs" onClick={exportToCSV} className="bg-zinc-950 border-zinc-900 text-zinc-400 hover:text-white rounded-lg gap-1">
            <Download className="h-3 w-3" /> CSV
          </Button>
          <Button variant="outline" size="xs" onClick={exportToExcel} className="bg-zinc-950 border-zinc-900 text-zinc-400 hover:text-white rounded-lg gap-1">
            <Download className="h-3 w-3" /> Excel
          </Button>
        </div>
      </div>

      {/* DYNAMIC SECTION WINDOWS */}
      {activeTab === "analytics" ? (
        <PlanAnalytics plans={plans} subscriptions={subscriptions} />
      ) : (
        <div className="space-y-6">
          
          {/* Filters Bar */}
          <div className="flex flex-col lg:flex-row gap-4 justify-between items-stretch lg:items-center bg-zinc-950 border border-zinc-900 p-4 rounded-2xl">
            <div className="relative flex-1">
              <Search className="absolute left-3.5 top-3 text-zinc-600 h-4 w-4" />
              <Input 
                placeholder="Search catalog by name, code, descriptors..." 
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="bg-zinc-900 border-zinc-850 pl-10 text-white rounded-xl placeholder-zinc-500 w-full"
              />
            </div>

            <div className="flex flex-wrap items-center gap-2">
              <Select value={selectedCategory} onValueChange={setSelectedCategory}>
                <SelectTrigger className="bg-zinc-900 border-zinc-850 text-xs rounded-xl w-36">
                  <SelectValue placeholder="Category" />
                </SelectTrigger>
                <SelectContent className="bg-zinc-950 border-zinc-900 text-zinc-300 text-xs">
                  <SelectItem value="All">All Categories</SelectItem>
                  <SelectItem value="Gourmet Fit">Gourmet Fit</SelectItem>
                  <SelectItem value="Health Clinical">Health Clinical</SelectItem>
                  <SelectItem value="Keto Shred">Keto Shred</SelectItem>
                  <SelectItem value="Athletic Peak">Athletic Peak</SelectItem>
                  <SelectItem value="Daily Simple">Daily Simple</SelectItem>
                </SelectContent>
              </Select>

              <Select value={selectedStatus} onValueChange={setSelectedStatus}>
                <SelectTrigger className="bg-zinc-900 border-zinc-850 text-xs rounded-xl w-32">
                  <SelectValue placeholder="Status" />
                </SelectTrigger>
                <SelectContent className="bg-zinc-950 border-zinc-900 text-zinc-300 text-xs">
                  <SelectItem value="All">All Status</SelectItem>
                  <SelectItem value="Active">Active</SelectItem>
                  <SelectItem value="Inactive">Inactive</SelectItem>
                  <SelectItem value="Draft">Draft</SelectItem>
                  <SelectItem value="Upcoming">Upcoming</SelectItem>
                  <SelectItem value="Archived">Archived</SelectItem>
                </SelectContent>
              </Select>

              <Select value={selectedDiet} onValueChange={setSelectedDiet}>
                <SelectTrigger className="bg-zinc-900 border-zinc-850 text-xs rounded-xl w-32">
                  <SelectValue placeholder="Diet Type" />
                </SelectTrigger>
                <SelectContent className="bg-zinc-950 border-zinc-900 text-zinc-300 text-xs">
                  <SelectItem value="All">All Diets</SelectItem>
                  <SelectItem value="Pure Veg">Pure Veg</SelectItem>
                  <SelectItem value="Vegan">Vegan</SelectItem>
                  <SelectItem value="Eggitarian">Eggitarian</SelectItem>
                  <SelectItem value="Non Veg">Non Veg</SelectItem>
                </SelectContent>
              </Select>

              {/* Column Visibility Trigger Button */}
              <div className="relative">
                <Button 
                  variant="outline" 
                  onClick={() => setShowColumnDropdown(!showColumnDropdown)} 
                  className="bg-zinc-900 border-zinc-850 rounded-xl gap-1.5 h-10 px-3 text-xs"
                >
                  <SlidersHorizontal className="h-3.5 w-3.5" /> Columns
                </Button>
                {showColumnDropdown && (
                  <div className="absolute right-0 mt-2 bg-zinc-950 border border-zinc-900 p-3 rounded-xl shadow-2xl z-20 w-48 space-y-2 text-xs">
                    <span className="font-bold text-zinc-400 block pb-1 border-b border-zinc-900 uppercase tracking-widest text-[10px]">Show Columns</span>
                    <div className="max-h-[220px] overflow-y-auto space-y-1.5 pr-1">
                      {Object.keys(visibleColumns).map((col) => (
                        <label key={col} className="flex items-center gap-2 cursor-pointer text-zinc-300 hover:text-white">
                          <input 
                            type="checkbox" 
                            checked={visibleColumns[col]} 
                            onChange={() => setVisibleColumns(prev => ({ ...prev, [col]: !prev[col] }))}
                            className="rounded bg-zinc-900 border-zinc-800 text-emerald-500 focus:ring-emerald-500 scale-95"
                          />
                          <span className="capitalize">{col.replace(/([A-Z])/g, ' $1')}</span>
                        </label>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* BULK ACTIONS BANNER PANEL */}
          {selectedPlanIds.length > 0 && (
            <div className="bg-emerald-950/20 border border-emerald-500/20 p-4 rounded-2xl flex items-center justify-between animate-in slide-in-from-top-2 duration-200">
              <div className="flex items-center gap-2 text-xs font-bold text-emerald-400">
                <CheckSquare className="h-4 w-4" />
                <span>{selectedPlanIds.length} plans selected for bulk adjustments</span>
              </div>
              <div className="flex items-center gap-2">
                <Button size="sm" onClick={() => handleBulkStatusChange("Active")} className="bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20 rounded-lg text-xs h-8">
                  Activate
                </Button>
                <Button size="sm" onClick={() => handleBulkStatusChange("Inactive")} className="bg-zinc-900 text-zinc-400 hover:bg-zinc-800 rounded-lg text-xs h-8">
                  Deactivate
                </Button>
                <Button size="sm" onClick={() => handleBulkStatusChange("Archived")} className="bg-zinc-900 text-zinc-400 hover:bg-zinc-800 rounded-lg text-xs h-8">
                  Archive
                </Button>
                <Button size="sm" onClick={handleBulkSoftDelete} className="bg-rose-950/40 text-rose-400 hover:bg-rose-950/60 rounded-lg text-xs h-8">
                  Delete (Soft)
                </Button>
                <Button size="sm" onClick={() => setSelectedPlanIds([])} variant="ghost" className="text-zinc-500 hover:text-zinc-300 text-xs h-8">
                  Clear
                </Button>
              </div>
            </div>
          )}

          {/* TABLE INTERFACE */}
          <div className="bg-zinc-950 border border-zinc-900 rounded-2xl overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-zinc-900/50 border-b border-zinc-900 text-zinc-500 uppercase tracking-widest text-[9px] font-bold sticky top-0 z-10">
                    <th className="p-4 w-12 text-center">
                      <button onClick={handleSelectAll} className="text-zinc-500 hover:text-zinc-300">
                        {selectedPlanIds.length === currentPlans.length && currentPlans.length > 0 ? (
                          <CheckSquare className="h-4 w-4 text-emerald-400" />
                        ) : (
                          <Square className="h-4 w-4" />
                        )}
                      </button>
                    </th>
                    {visibleColumns.image && <th className="p-4 w-16">Image</th>}
                    {visibleColumns.name && <th className="p-4">Plan / Descriptor</th>}
                    {visibleColumns.code && <th className="p-4">Code</th>}
                    {visibleColumns.category && <th className="p-4">Category</th>}
                    {visibleColumns.duration && <th className="p-4">Cycle</th>}
                    {visibleColumns.mealsPerDay && <th className="p-4">Meals/Day</th>}
                    {visibleColumns.totalMeals && <th className="p-4">Meals</th>}
                    {visibleColumns.dietType && <th className="p-4">Diet Type</th>}
                    {visibleColumns.goal && <th className="p-4">Goal</th>}
                    {visibleColumns.nutrition && <th className="p-4">Nutritions</th>}
                    {visibleColumns.price && <th className="p-4">Pricing (INR)</th>}
                    {visibleColumns.subscribers && <th className="p-4">Subs</th>}
                    {visibleColumns.revenue && <th className="p-4">Est. Revenue</th>}
                    {visibleColumns.status && <th className="p-4">Status</th>}
                    {visibleColumns.actions && <th className="p-4 text-right">Actions</th>}
                  </tr>
                </thead>
                <tbody className="divide-y divide-zinc-900/60 text-xs">
                  {loading ? (
                    <tr>
                      <td colSpan={16} className="p-16 text-center text-zinc-500">
                        <div className="flex flex-col items-center justify-center gap-2">
                          <Loader2 className="h-8 w-8 animate-spin text-emerald-500" />
                          <span className="font-bold text-zinc-400">Syncing subscription catalogs...</span>
                        </div>
                      </td>
                    </tr>
                  ) : currentPlans.length === 0 ? (
                    <tr>
                      <td colSpan={16} className="p-16 text-center text-zinc-500">
                        <div className="flex flex-col items-center justify-center gap-2">
                          <AlertTriangle className="h-8 w-8 text-zinc-700" />
                          <span className="font-bold text-zinc-400">No subscription plans formulate found</span>
                          <p className="text-zinc-600 text-[11px] mt-1">Adjust filters or click "Formulate Plan" to start drafting</p>
                        </div>
                      </td>
                    </tr>
                  ) : (
                    currentPlans.map((plan) => {
                      const isSelected = selectedPlanIds.includes(plan.id)
                      const subsCount = getSubscribersForPlan(plan.id)
                      const revEst = getMonthlyRevenueForPlan(plan)
                      return (
                        <tr 
                          key={plan.id} 
                          className={`hover:bg-zinc-900/30 transition-all ${
                            isSelected ? "bg-emerald-500/5" : ""
                          }`}
                        >
                          <td className="p-4 text-center">
                            <button onClick={() => handleSelectRow(plan.id)} className="text-zinc-600 hover:text-zinc-400">
                              {isSelected ? (
                                <CheckSquare className="h-4 w-4 text-emerald-400" />
                              ) : (
                                <Square className="h-4 w-4" />
                              )}
                            </button>
                          </td>
                          {visibleColumns.image && (
                            <td className="p-4">
                              <img 
                                src={plan.thumbnail || plan.imageUrl || "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=100&auto=format&fit=crop&q=80"} 
                                alt="thumbnail" 
                                className="h-10 w-10 rounded-xl object-cover border border-zinc-900/50" 
                              />
                            </td>
                          )}
                          {visibleColumns.name && (
                            <td className="p-4">
                              <div className="space-y-0.5">
                                <span className="font-bold text-white text-sm hover:text-emerald-400 cursor-pointer block truncate max-w-[180px]" onClick={() => setPreviewPlan(plan)}>
                                  {plan.planName || plan.name}
                                </span>
                                {plan.badge && (
                                  <Badge className="bg-amber-500/10 text-amber-400 border-amber-500/20 text-[9px] uppercase font-bold px-1 py-0 scale-95 origin-left">
                                    {plan.badge}
                                  </Badge>
                                )}
                              </div>
                            </td>
                          )}
                          {visibleColumns.code && (
                            <td className="p-4 font-mono font-bold text-zinc-400">{plan.planCode || "TB-N/A"}</td>
                          )}
                          {visibleColumns.category && (
                            <td className="p-4 text-zinc-400 font-medium">{plan.category || "Gourmet Fit"}</td>
                          )}
                          {visibleColumns.duration && (
                            <td className="p-4 font-semibold text-white">{plan.duration || 30} Days</td>
                          )}
                          {visibleColumns.mealsPerDay && (
                            <td className="p-4 text-zinc-400 font-bold">{plan.mealsPerDay || 2} / day</td>
                          )}
                          {visibleColumns.totalMeals && (
                            <td className="p-4 text-zinc-400 font-bold">{plan.totalMeals || (plan.duration * plan.mealsPerDay)}</td>
                          )}
                          {visibleColumns.dietType && (
                            <td className="p-4">
                              <Badge className={`text-[10px] rounded-lg ${
                                plan.dietType === "Pure Veg" ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20" :
                                plan.dietType === "Vegan" ? "bg-teal-500/10 text-teal-400 border-teal-500/20" :
                                plan.dietType === "Eggitarian" ? "bg-amber-500/10 text-amber-400 border-amber-500/20" :
                                "bg-rose-500/10 text-rose-400 border-rose-500/20"
                              }`}>
                                {plan.dietType || "Pure Veg"}
                              </Badge>
                            </td>
                          )}
                          {visibleColumns.goal && (
                            <td className="p-4 font-medium text-zinc-400 truncate max-w-[120px]">{plan.goal || "Balanced"}</td>
                          )}
                          {visibleColumns.nutrition && (
                            <td className="p-4">
                              <div className="space-y-0.5 font-mono text-[10px] text-zinc-400">
                                <div><strong className="text-zinc-200">{plan.calories || 1200}</strong> kcal</div>
                                <div><strong className="text-zinc-200">{plan.protein || 60}g</strong> prot</div>
                              </div>
                            </td>
                          )}
                          {visibleColumns.price && (
                            <td className="p-4">
                              <div className="space-y-0.5">
                                <span className="font-bold text-white block">₹{(plan.offerPrice || plan.price || 0).toLocaleString()}</span>
                                {plan.price > plan.offerPrice && (
                                  <span className="text-[10px] text-zinc-500 line-through block">₹{plan.price.toLocaleString()}</span>
                                )}
                              </div>
                            </td>
                          )}
                          {visibleColumns.subscribers && (
                            <td className="p-4 font-bold text-white">{subsCount}</td>
                          )}
                          {visibleColumns.revenue && (
                            <td className="p-4 font-black text-emerald-400">₹{revEst.toLocaleString()}</td>
                          )}
                          {visibleColumns.status && (
                            <td className="p-4">
                              <Badge className={`text-[9px] font-black uppercase ${
                                plan.status === "Active" ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20" :
                                plan.status === "Inactive" ? "bg-zinc-800 text-zinc-500 border-zinc-700" :
                                plan.status === "Draft" ? "bg-amber-500/10 text-amber-400 border-amber-500/20" :
                                plan.status === "Upcoming" ? "bg-indigo-500/10 text-indigo-400 border-indigo-500/20" :
                                "bg-rose-500/10 text-rose-400 border-rose-500/20"
                              }`}>
                                {plan.status}
                              </Badge>
                            </td>
                          )}
                          {visibleColumns.actions && (
                            <td className="p-4 text-right">
                              <div className="flex items-center justify-end gap-1.5">
                                <Button 
                                  variant="ghost" 
                                  size="icon" 
                                  onClick={() => setPreviewPlan(plan)}
                                  className="h-8 w-8 text-zinc-400 hover:text-white rounded-lg hover:bg-zinc-900"
                                >
                                  <Eye className="h-4 w-4" />
                                </Button>
                                <Button 
                                  variant="ghost" 
                                  size="icon" 
                                  onClick={() => {
                                    setEditingPlan(plan)
                                    setIsWizardOpen(true)
                                  }}
                                  className="h-8 w-8 text-zinc-400 hover:text-white rounded-lg hover:bg-zinc-900"
                                >
                                  <Edit2 className="h-4 w-4" />
                                </Button>
                                <Button 
                                  variant="ghost" 
                                  size="icon" 
                                  onClick={() => handleDuplicate(plan.id)}
                                  className="h-8 w-8 text-zinc-400 hover:text-white rounded-lg hover:bg-zinc-900"
                                >
                                  <Copy className="h-4 w-4" />
                                </Button>
                                <Button 
                                  variant="ghost" 
                                  size="icon" 
                                  onClick={() => handleArchive(plan.id)}
                                  className="h-8 w-8 text-zinc-400 hover:text-amber-400 rounded-lg hover:bg-zinc-900"
                                >
                                  <Archive className="h-4 w-4" />
                                </Button>
                                <Button 
                                  variant="ghost" 
                                  size="icon" 
                                  onClick={() => handleSoftDelete(plan.id)}
                                  className="h-8 w-8 text-zinc-500 hover:text-rose-400 rounded-lg hover:bg-zinc-900"
                                >
                                  <Trash2 className="h-4 w-4" />
                                </Button>
                              </div>
                            </td>
                          )}
                        </tr>
                      )
                    })
                  )}
                </tbody>
              </table>
            </div>

            {/* Pagination Controls */}
            {totalPages > 1 && (
              <div className="p-4 border-t border-zinc-900 flex justify-between items-center bg-zinc-950 text-xs">
                <span className="text-zinc-500 font-bold">Showing plans {(currentPage - 1) * itemsPerPage + 1} to {Math.min(currentPage * itemsPerPage, filteredPlans.length)} of {filteredPlans.length}</span>
                <div className="flex gap-1">
                  <Button
                    variant="outline"
                    disabled={currentPage === 1}
                    onClick={() => setCurrentPage(prev => Math.max(1, prev - 1))}
                    className="h-8 rounded-lg border-zinc-900 text-zinc-400"
                  >
                    Previous
                  </Button>
                  {[...Array(totalPages)].map((_, i) => (
                    <Button
                      key={i}
                      onClick={() => setCurrentPage(i + 1)}
                      className={`h-8 w-8 rounded-lg text-xs ${
                        currentPage === i + 1 
                          ? "bg-emerald-500 text-black font-black" 
                          : "bg-zinc-900 text-zinc-400 hover:text-white"
                      }`}
                    >
                      {i + 1}
                    </Button>
                  ))}
                  <Button
                    variant="outline"
                    disabled={currentPage === totalPages}
                    onClick={() => setCurrentPage(prev => Math.min(totalPages, prev + 1))}
                    className="h-8 rounded-lg border-zinc-900 text-zinc-400"
                  >
                    Next
                  </Button>
                </div>
              </div>
            )}
          </div>

        </div>
      )}

      {/* CREATE / EDIT PLAN WIZARD (11 STEPS MODAL) */}
      <PlanWizard 
        isOpen={isWizardOpen}
        onClose={() => {
          setIsWizardOpen(false)
          setEditingPlan(null)
        }}
        onSave={handleSavePlan}
        editingPlan={editingPlan}
      />

      {/* PREVIEW DETAILED SHEET/MODAL */}
      <AnimatePresence>
        {previewPlan && (
          <div className="fixed inset-0 bg-black/85 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-zinc-950 border border-zinc-900 rounded-3xl w-full max-w-2xl max-h-[90vh] overflow-y-auto shadow-2xl relative"
            >
              <button 
                onClick={() => setPreviewPlan(null)}
                className="absolute right-4 top-4 text-zinc-500 hover:text-white bg-zinc-900/50 p-1.5 rounded-full z-10"
              >
                <X className="h-4 w-4" />
              </button>

              <div className="relative h-48 w-full overflow-hidden">
                <div className="absolute inset-0 bg-gradient-to-t from-zinc-950 via-zinc-950/20 to-transparent z-10" />
                <img 
                  src={previewPlan.thumbnail || previewPlan.imageUrl} 
                  alt="cover" 
                  className="w-full h-full object-cover" 
                />
                <div className="absolute bottom-4 left-6 z-20 space-y-1.5">
                  <Badge className="bg-emerald-500/10 text-emerald-400 border-emerald-500/20 text-[10px] font-black uppercase">
                    {previewPlan.category || "Gourmet Fit"}
                  </Badge>
                  <h2 className="text-2xl font-black text-white">{previewPlan.planName || previewPlan.name}</h2>
                </div>
              </div>

              <div className="p-6 space-y-6">
                <div className="flex items-center justify-between border-b border-zinc-900 pb-4">
                  <div className="space-y-0.5">
                    <span className="text-[10px] text-zinc-500 uppercase font-black">Plan Code</span>
                    <span className="text-sm font-bold text-zinc-300 block font-mono">{previewPlan.planCode || "TB-N/A"}</span>
                  </div>
                  <div className="space-y-0.5 text-right">
                    <span className="text-[10px] text-zinc-500 uppercase font-black">Price per cycle</span>
                    <span className="text-xl font-black text-emerald-400 block">₹{(previewPlan.offerPrice || previewPlan.price).toLocaleString()}</span>
                  </div>
                </div>

                <div className="grid grid-cols-3 gap-4">
                  <div className="bg-zinc-900/40 p-4 rounded-xl space-y-0.5 text-center">
                    <span className="text-[10px] text-zinc-500 uppercase font-bold">Duration</span>
                    <span className="text-base font-black text-white block">{previewPlan.duration} Days</span>
                  </div>
                  <div className="bg-zinc-900/40 p-4 rounded-xl space-y-0.5 text-center">
                    <span className="text-[10px] text-zinc-500 uppercase font-bold">Total Meals</span>
                    <span className="text-base font-black text-white block">{previewPlan.totalMeals || (previewPlan.duration * previewPlan.mealsPerDay)}</span>
                  </div>
                  <div className="bg-zinc-900/40 p-4 rounded-xl space-y-0.5 text-center">
                    <span className="text-[10px] text-zinc-500 uppercase font-bold">Diet Type</span>
                    <span className="text-base font-black text-emerald-400 block">{previewPlan.dietType || "Pure Veg"}</span>
                  </div>
                </div>

                <div className="space-y-2">
                  <h3 className="text-xs font-black text-white uppercase tracking-wider">Plan Description</h3>
                  <p className="text-xs text-zinc-400 leading-relaxed">{previewPlan.description || "No full description formulated yet."}</p>
                </div>

                {/* Nutrition Macros */}
                <div className="space-y-2.5 border-t border-zinc-900 pt-4">
                  <h3 className="text-xs font-black text-white uppercase tracking-wider">Macros Formulation (Per Day)</h3>
                  <div className="grid grid-cols-4 gap-2">
                    {[
                      { label: "Calories", val: `${previewPlan.calories || 1200} kcal` },
                      { label: "Protein", val: `${previewPlan.protein || 60} g` },
                      { label: "Carbs", val: `${previewPlan.carbs || 120} g` },
                      { label: "Fats", val: `${previewPlan.fat || 40} g` }
                    ].map((m, i) => (
                      <div key={i} className="bg-zinc-900/20 p-2.5 rounded-lg text-center text-xs">
                        <span className="text-zinc-500 block">{m.label}</span>
                        <strong className="text-zinc-200 mt-0.5 block">{m.val}</strong>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Service areas included */}
                {previewPlan.serviceAreas && previewPlan.serviceAreas.length > 0 && (
                  <div className="space-y-2.5 border-t border-zinc-900 pt-4">
                    <h3 className="text-xs font-black text-white uppercase tracking-wider">Geo-Distribution Zones</h3>
                    <div className="flex flex-wrap gap-1.5">
                      {previewPlan.serviceAreas.map((areaId: string, i: number) => (
                        <Badge key={i} className="bg-zinc-900 text-zinc-400 border-zinc-800 font-mono text-[9px]">
                          Zone-{areaId.slice(0,6)}
                        </Badge>
                      ))}
                    </div>
                  </div>
                )}

                {/* Add-on Up-sells */}
                {previewPlan.addons && previewPlan.addons.length > 0 && (
                  <div className="space-y-2.5 border-t border-zinc-900 pt-4">
                    <h3 className="text-xs font-black text-white uppercase tracking-wider">Pre-Approved Add-ons Menu</h3>
                    <div className="grid grid-cols-2 gap-2">
                      {previewPlan.addons.map((addon: any, i: number) => (
                        <div key={i} className="bg-zinc-900/10 p-2 rounded-lg flex items-center gap-2 border border-zinc-900/50">
                          <img src={addon.image} className="h-8 w-8 rounded-md object-cover" />
                          <div className="min-w-0">
                            <span className="text-[10px] font-bold text-white block truncate">{addon.name}</span>
                            <span className="text-[9px] text-emerald-400 block">₹{addon.price}</span>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

    </div>
  )
}
